// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxsqnJMxENTpG4fF2TovEJ2h6uuFCjMsI',
    appId: '1:928279287020:web:8be7e091332c8f2d4ac1c9',
    messagingSenderId: '928279287020',
    projectId: 'adaptative-user-interface',
    authDomain: 'adaptative-user-interface.firebaseapp.com',
    storageBucket: 'adaptative-user-interface.firebasestorage.app',
    measurementId: 'G-1FPVSRFXYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4a3rTuaqhiPwWcLXuJMtTNoVOuc5I2U',
    appId: '1:928279287020:android:121a7fcc0cd2ebf14ac1c9',
    messagingSenderId: '928279287020',
    projectId: 'adaptative-user-interface',
    storageBucket: 'adaptative-user-interface.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGoirCo65p0-ZERtBpqCeR6d3dTqDYuk',
    appId: '1:928279287020:ios:f19eca3d26a8c75e4ac1c9',
    messagingSenderId: '928279287020',
    projectId: 'adaptative-user-interface',
    storageBucket: 'adaptative-user-interface.firebasestorage.app',
    iosBundleId: 'com.example.osiSolucoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxsqnJMxENTpG4fF2TovEJ2h6uuFCjMsI',
    appId: '1:928279287020:web:3477ff973eb792ed4ac1c9',
    messagingSenderId: '928279287020',
    projectId: 'adaptative-user-interface',
    authDomain: 'adaptative-user-interface.firebaseapp.com',
    storageBucket: 'adaptative-user-interface.firebasestorage.app',
    measurementId: 'G-9SV74YHDG9',
  );
}
